### ISSUE TITLE
Hashing incorrect?

### ISSUE THREAD

**Issue by leuchtdiode** [hochstrasserio/wirecard#10]
First of all, thanks for this great library. I used it the last couples week with the TEST customer-ID (D200001) and everything worked fine. Yesterday I got my LIVE account, changed Customer-ID/Secret and after redirect to checkout page I got "FINGERPRINT is invalid". With Wirecard help and a log file from their system I could debug your library and found out that the requestFingerprint is not being calculated correctly. Here is my solution which I think could go in to your code, although I have no idea if some other accounts could be affected?

Class Hochstrasser\Wirecard\Fingerprint (line 62):

`return hash('sha512', $raw);`

to

`return hash_hmac('sha512', $raw, $this->parameters['secret']);`

BR,
Alex

**Comment by leuchtdiode** [comment]
Looks like Wirecard can change something in the user account. Now my workaround isn't necessary any longer because they changed something which makes the library work again.

But maybe considering to address this "issue" anyway?

**Comment by CHH** [comment]
Thank you for raising this issue 😄 

I've noticed a couple weeks ago in their docs that they now say that SHA512 with HMAC should be used to compute the fingerprint. But the tests still ran fine at that time, so I thought that they are still in a transitioning period and I might not need to do something. Our projects also are still running fine.

There are many settings that the customer support of Wirecard can set, apparently including which hashing method is used.

I think a setting to set the fingerprint compute mode would be the best solution to this problem, defaulting to the new method. I'll look how this works with the demo account.

**Comment by CHH** [comment]
And sorry for not getting back to you earlier. I'm drowning in Github notifications 😫
