### ISSUE TITLE
Update basket model for shopping basket data

### ISSUE THREAD

**Issue by CHH** [hochstrasserio/wirecard#15]
https://guides.wirecard.at/request_parameters#optional_parameters

**Comment by Estigy** [comment]
I just stumbled across the same issue. Using verion 0.2 of this library, I add some items to the basket, but they never get displayed on the Wirecard checkout page. All I see is the amount the user has to pay.

There have been some changes regarding the mandatory fields if basket data is being used.

**Comment by Estigy** [comment]
I'm going to come up with a pull request within the next days.

**Comment by CHH** [comment]
@Estigy that would be great!

**Comment by Estigy** [comment]
I just created a pull request for you. Please have a look at it.

**Comment by CHH** [comment]
@Estigy Thanks! I'll have a look.

**Comment by CHH** [comment]
PR in #20

**Comment by CHH** [comment]
PR landed in master.
