### ISSUE TITLE
hash in Test / Production Mode

### ISSUE THREAD

**Issue by varioous** [hochstrasserio/wirecard#23]
Hello again,

in Test-Mode and Production-Mode you have to calculate the fingerprint not just with the hash, instead use the hmac and has.

So i changed in Fingerprint.php in Line 102 to: 
`return hash_hmac('sha512', $raw, $this->context->getSecret());`

Maybe you also want to change it in the source.

Again - Thanks for your great work -> saved me a lot of time integrating Wirecard Checkout Seamless.

Greets,
Harald

**Comment by CHH** [comment]
Fixed in #10
