### ISSUE TITLE
Request | Please release minor fix versions

### ISSUE THREAD

**Issue by bensbox** [hochstrasserio/wirecard#26]
@CHH : Could you release minor versions (like 1.0.1 or 1.0.2), as soon as a fix has been merged or added to the codebase like the one for the missing fingerprint parameters or my risk_suppress option?
That way, we can update the codebase faster without waiting for the next feature release or running on the potentially not fully tested master branch :)

Thanks alot!

**Comment by CHH** [comment]
Sure, will do.

**Comment by CHH** [comment]
v1.1.0 is tagged and live on Packagist.

**Comment by bensbox** [comment]
Oh wow, already v1.1. Isn't this mixing up your milestone handling? https://github.com/hochstrasserio/wirecard/milestone/2

That's why i suggested a v1.0.1 or v1.0.2

**Comment by bensbox** [comment]
@CHH : Just to make sure - is the v1.1 final? Please see my comment above.

**Comment by CHH** [comment]
@bensbox yes it's final, it's tagged and on Packagist, so there's no way back

**Comment by CHH** [comment]
@bensbox moved the 1.1 milestone issues to a 1.2 milestone. I wanted to tag this 1.1 because there are a couple features in there, not only bugfixes, and there hasn't been a release in the last months.

**Comment by bensbox** [comment]
Great - thanks for clarification!
