### ISSUE TITLE
Javascript rendering

### ISSUE THREAD

**Issue by itviventura** [hochstrasserio/wirecard#32]
Hi There,

First of all thanks a lot with this great plugin to integrate wirecard but I have a question how we can integrate the Wirecard Seamless Checkout implementation into javascript the fact is that we are using a Single Page Application and we have made tests in everything is working well when we just use the server rendering that with javascript rendering we don't know what approach we need to follow,

Can you help me with this?, Thanks a lot.

**Comment by CHH** [comment]
An approach that I imagine could work (I‘ve no way of testing it right now) would be to have the client make a request to your server, then have the server prepare the payment with InitDataStorageRequest. This returns a JS URL, which can be returned to the client along with the data storage ID. The client then would insert a script tag into the document head with the `src` attribute set to the returned JS URL. 

Register an `onload` listener on the script tag and call the JS methods provided by Wirecard in the onload listener (so you only call once the JS is fully loaded). The wirecard methods store the data in the data storage. When data was saved in the data storage send the data storage ID to the server, so the payment request can use it as a param.

Hope that helps.
